on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 2 * * */1'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check api
        run: |
          if curl -L -x "" -k --connect-timeout 5 "https://www.als.ogcio.gov.hk/lookup?q=aaa"; then
              echo "ok";
          else
              exit 1;
          fi;
          
      - name: Send mail
        if: ${{ failure() }}
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.sendgrid.net
          port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ALS APIs fail
          body: Job ${{job.status}}
          to: ${{secrets.MAIL_TO}}
          from: ${{secrets.MAIL_FROM}}
