# This is a basic workflow to help you get started with Actions

name: ssl

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * */1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          if curl -L -x "" -k --connect-timeout 5 "https://www.als.ogcqwecqwio.gov.hk/lookup?q=uptime"; then
              echo "ok";
          else
              exit 1;
          fi;
          
      - name: Send mail
        if: ${{ failure() }}
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.sendgrid.net
          port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ALS APIs fail
          body: Job ${{job.status}}
          to: ${{secrets.MAIL_TO}}
          from: ${{secrets.MAIL_FROM}}
