# This is a basic workflow to help you get started with Actions

name: ssl

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          target_date=`echo "oh" | openssl s_client -connect www.als.ogcio.gov.hk:443 2>/dev/null | openssl x509 -noout -dates | grep 'notAfter=' | cut  -f2 -d "="`
          today=`echo $(($(date --utc --date "$1" +%s)/86400))`
          target=`echo $(($(date --utc --date "$target_date" +%s)/86400))`
          days=`expr $target - $today`
          echo "$days days until $target_date"
          if (($days < 3000)); then exit 1; fi
          
      - name: Send mail
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.sendgrid.net
          # Required mail server port:
          server_port: 465
          # Required mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Required mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: uild job of ${{github.repository}} completed FAIL!
          # Required recipients' addresses:
          to: kwltu@ogcio.gov.hk
          # Required sender full name (address can be skipped):
          from: kwltu@ogcio.gov.hk
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
