# This is a basic workflow to help you get started with Actions

name: ssl

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  monitor:
    name: SSL/TLS Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Monitor
        uses: bluenovaio/action-tls-monitor@main
        with: 
          domain: www.als.ogcio.gov.hk
          expiration_days: 30
          approved_protocols: TLSv1.2,TLSv1.3
          alert_method: slack
          alert_token: ${{ secrets.SLACK_WEBHOOK_URL }}
